uvmf:
  environments:
    execute:
      agents:
      - initiator_responder: INITIATOR
        name: agent_in
        type: execute_in
      - initiator_responder: RESPONDER
        name: agent_out
        type: execute_out
      analysis_components:
      - name: execute_pred
        parameters: []
        type: execute_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: execute_scbd
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: execute_out_transaction
      subenvs: []
      tlm_connections:
      - driver: agent_in.monitored_ap
        receiver: execute_pred.analysis_export
        validate: 'True'
      - driver: execute_pred.analysis_port
        receiver: execute_scbd.expected_analysis_export
        validate: 'True'
      - driver: agent_out.monitored_ap
        receiver: execute_scbd.actual_analysis_export
        validate: 'True'
